apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinel

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - migrate-job.yaml
  - api.yaml
  - frontend.yaml
  - ingress.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: sentinel
    includeSelectors: false

images:
  - name: sentinel-api
    newTag: "0.3.0"
  - name: sentinel-frontend
    newTag: "0.3.0"
  - name: sentinel-migrate
    newTag: "0.3.0"
