{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel.secretName" . }}
  namespace: {{ include "sentinel.namespace" . }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  DATABASE_URL: {{ include "sentinel.databaseUrl" . | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  TOTP_ENCRYPTION_KEY: {{ .Values.secrets.totpEncryptionKey | quote }}
  SECRETS_ENCRYPTION_KEY: {{ .Values.secrets.secretsEncryptionKey | quote }}
  SENTINEL_BOOTSTRAP_ADMIN_EMAIL: {{ .Values.secrets.bootstrapAdminEmail | quote }}
  SENTINEL_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.secrets.bootstrapAdminPassword | quote }}
  {{- range $k, $v := .Values.secrets.extra }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
